# Generated by Django 4.1.4 on 2022-12-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("readlist_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="descritpion",
            new_name="description",
        ),
    ]
